Makefile: use latest mxdev.
That hopefully fixes [test failures](https://github.com/collective/collective.tiles.carousel/actions/runs/31401338970/job/93496786314?pr=16):

```
nstalling collected packages: libvcs, mxdev

Successfully installed libvcs-0.11.1 mxdev-2.1.0
Prepare sources and dependencies
Traceback (most recent call last):
  File "/home/runner/work/collective.tiles.carousel/collective.tiles.carousel/./venv/bin/mxdev", line 3, in <module>
    from mxdev import main
  File "/home/runner/work/collective.tiles.carousel/collective.tiles.carousel/venv/lib/python3.13/site-packages/mxdev.py", line 4, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

Locally it is still failing, but maybe that is because I have a bad internet connection:

```
WARNING: lxml 5.3.0 does not provide the extra 'cssselect'
ERROR: Cannot install five.intid because these package versions have conflicting dependencies.

The conflict is caused by:
    accesscontrol 7.2 depends on RestrictedPython>=7.4
    The user requested (constraint) restrictedpython==8.0

Additionally, some packages in these conflicts have no matching distributions available for your environment:
    restrictedpython
```